runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /fonts
  static_dir: fonts
- url: /img
  static_dir: img
- url: /less
  static_dir: less
- url: /vendor
  static_dir: vendor
- url: /style.css
  static_files: style.css
  upload: style.css
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest